spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
